//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyAdjudicator.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressType
    {
        public AddressType()
        {
            this.PatientAddress = new HashSet<PatientAddress>();
        }
    
        public string AddressTypeCode { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<PatientAddress> PatientAddress { get; set; }
    }
}
