//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyAdjudicator.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtomGroup
    {
        public AtomGroup()
        {
            this.AtomGroupItems = new HashSet<AtomGroupItems>();
            this.AtomGroupItems1 = new HashSet<AtomGroupItems>();
            this.Implications = new HashSet<Implication>();
        }
    
        public int AtomGroupId { get; set; }
        public string LogicalOperator { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<AtomGroupItems> AtomGroupItems { get; set; }
        public virtual ICollection<AtomGroupItems> AtomGroupItems1 { get; set; }
        public virtual ICollection<Implication> Implications { get; set; }
    }
}
