//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyAdjudicator.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtomDetail
    {
        public AtomDetail()
        {
            this.AtomDetail1 = new HashSet<AtomDetail>();
        }
    
        public System.Guid RecordId { get; set; }
        public System.Guid AtomId { get; set; }
        public string Class { get; set; }
        public string Property { get; set; }
        public string Value { get; set; }
        public string Operation { get; set; }
        public bool Retraction { get; set; }
        public Nullable<System.Guid> OriginalFactRecordId { get; set; }
        public System.DateTime RecordCreatedDateTime { get; set; }
        public string RecordCreatedUser { get; set; }
    
        public virtual Atom Atom { get; set; }
        public virtual ICollection<AtomDetail> AtomDetail1 { get; set; }
        public virtual AtomDetail AtomDetail2 { get; set; }
    }
}
