//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyAdjudicator.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtomGroupItem
    {
        public System.Guid RecordId { get; set; }
        public System.Guid AtomGroupId { get; set; }
        public Nullable<System.Guid> AtomId { get; set; }
        public Nullable<System.Guid> ContainedAtomGroupId { get; set; }
        public int Priority { get; set; }
        public bool Retraction { get; set; }
        public Nullable<System.Guid> OriginalFactRecordId { get; set; }
        public System.DateTime RecordCreatedDateTime { get; set; }
        public string RecordCreatedUser { get; set; }
    
        public virtual AtomGroup AtomGroup { get; set; }
        public virtual Atom Atom { get; set; }
        public virtual AtomGroup AtomGroup1 { get; set; }
    }
}
