//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyAdjudicator.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Atom
    {
        public Atom()
        {
            this.RecordDeleteUser = "";
            this.AtomGroupItems = new HashSet<AtomGroupItem>();
            this.Implication = new HashSet<Implication>();
        }
    
        public System.Guid AtomId { get; set; }
        public string Class { get; set; }
        public string Property { get; set; }
        public string Value { get; set; }
        public string Operation { get; set; }
        public System.DateTime RecordCreatedDateTime { get; set; }
        public string RecordCreatedUser { get; set; }
        public Nullable<System.DateTime> RecordDeleteDate { get; set; }
        public string RecordDeleteUser { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<AtomGroupItem> AtomGroupItems { get; set; }
        public virtual ICollection<Implication> Implication { get; set; }
    }
}
