//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyAdjudicator.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtomGroupItems
    {
        public int RecordId { get; set; }
        public int AtomGroupId { get; set; }
        public Nullable<int> AtomId { get; set; }
        public Nullable<int> ContainedAtomGroupId { get; set; }
        public int Priority { get; set; }
    
        public virtual AtomGroup AtomGroup { get; set; }
        public virtual Atom Atom { get; set; }
        public virtual AtomGroup AtomGroup1 { get; set; }
    }
}
