//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyAdjudicator.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientDetail
    {
        public ClientDetail()
        {
            this.ClientDetail1 = new HashSet<ClientDetail>();
        }
    
        public System.Guid RecordId { get; set; }
        public string ClientId { get; set; }
        public string Name { get; set; }
        public bool Retraction { get; set; }
        public Nullable<System.Guid> OriginalFactRecordId { get; set; }
        public System.DateTime RecordCreatedDateTime { get; set; }
        public string RecordCreatedUser { get; set; }
        public System.Guid ClientInternalId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<ClientDetail> ClientDetail1 { get; set; }
        public virtual ClientDetail ClientDetail2 { get; set; }
    }
}
