//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyAdjudicator.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientGroup
    {
        public ClientGroup()
        {
            this.ClientGroup1 = new HashSet<ClientGroup>();
        }
    
        public System.Guid RecordId { get; set; }
        public System.Guid ClientInternalId { get; set; }
        public System.Guid GroupInternalId { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public bool Retraction { get; set; }
        public Nullable<System.Guid> OriginalFactRecordId { get; set; }
        public System.DateTime RecordCreatedDateTime { get; set; }
        public string RecordCreatedUser { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Group Group { get; set; }
        public virtual ICollection<ClientGroup> ClientGroup1 { get; set; }
        public virtual ClientGroup ClientGroup2 { get; set; }
    }
}
