//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyAdjudicator.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.ClientDetails = new HashSet<ClientDetail>();
            this.ClientGroup = new HashSet<ClientGroup>();
        }
    
        public System.Guid ClientInternalId { get; set; }
        public System.DateTime RecordCreatedDateTime { get; set; }
        public string RecordCreatedUser { get; set; }
    
        public virtual ICollection<ClientDetail> ClientDetails { get; set; }
        public virtual ICollection<ClientGroup> ClientGroup { get; set; }
    }
}
