//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyAdjudicator.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.GroupFacts = new HashSet<GroupDetail>();
            this.PatientGroups = new HashSet<PatientGroup>();
            this.ClientGroup = new HashSet<ClientGroup>();
            this.GroupPlan = new HashSet<GroupPlan>();
        }
    
        public System.Guid GroupInternalId { get; set; }
        public System.DateTime RecordCreatedDateTime { get; set; }
        public string RecordCreatedUser { get; set; }
    
        public virtual ICollection<GroupDetail> GroupFacts { get; set; }
        public virtual ICollection<PatientGroup> PatientGroups { get; set; }
        public virtual ICollection<ClientGroup> ClientGroup { get; set; }
        public virtual ICollection<GroupPlan> GroupPlan { get; set; }
    }
}
