//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyAdjudicator.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupDetail
    {
        public GroupDetail()
        {
            this.GroupDetail1 = new HashSet<GroupDetail>();
        }
    
        public System.Guid RecordId { get; set; }
        public string Name { get; set; }
        public string GroupId { get; set; }
        public bool Retraction { get; set; }
        public Nullable<System.Guid> OriginalFactRecordId { get; set; }
        public System.DateTime RecordCreatedDateTime { get; set; }
        public string RecordCreatedUser { get; set; }
        public System.Guid GroupInternalId { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual ICollection<GroupDetail> GroupDetail1 { get; set; }
        public virtual GroupDetail GroupDetail2 { get; set; }
    }
}
