//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyAdjudicator.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Implication
    {
        public Implication()
        {
            this.AtomGroups = new HashSet<AtomGroup>();
            this.RuleImplications = new HashSet<RuleImplication>();
        }
    
        public int ImplicationId { get; set; }
        public string AtomGroupId { get; set; }
        public int DeductionAtomId { get; set; }
    
        public virtual ICollection<AtomGroup> AtomGroups { get; set; }
        public virtual ICollection<RuleImplication> RuleImplications { get; set; }
    }
}
