//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyAdjudicator.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientAddress
    {
        public PatientAddress()
        {
            this.PatientAddress1 = new HashSet<PatientAddress>();
        }
    
        public System.Guid RecordId { get; set; }
        public long PatientId { get; set; }
        public string AddressTypeCode { get; set; }
        public System.Guid AddressId { get; set; }
        public bool Retraction { get; set; }
        public Nullable<System.Guid> OriginalFactRecordId { get; set; }
        public System.DateTime RecordCreatedDateTime { get; set; }
        public string RecordCreatedUser { get; set; }
        public int Slot { get; set; }
    
        public virtual AddressType AddressType { get; set; }
        public virtual Address Address { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual ICollection<PatientAddress> PatientAddress1 { get; set; }
        public virtual PatientAddress PatientAddress2 { get; set; }
    }
}
