//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyAdjudicator.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientDetail
    {
        public PatientDetail()
        {
            this.PatientDetail1 = new HashSet<PatientDetail>();
        }
    
        public System.Guid RecordId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string CardholderId { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string PersonCode { get; set; }
        public string PatientRelationshipCode { get; set; }
        public string Gender { get; set; }
        public bool Retraction { get; set; }
        public Nullable<System.Guid> OriginalFactRecordId { get; set; }
        public System.DateTime RecordCreatedDateTime { get; set; }
        public string RecordCreatedUser { get; set; }
        public long PatientId { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual ICollection<PatientDetail> PatientDetail1 { get; set; }
        public virtual PatientDetail PatientDetail2 { get; set; }
    }
}
