//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyAdjudicator.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PharmacyClaimAdjudicatorEntities : DbContext
    {
        public PharmacyClaimAdjudicatorEntities()
            : base("name=PharmacyClaimAdjudicatorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Group> Group { get; set; }
        public DbSet<GroupFact> GroupFact { get; set; }
        public DbSet<Patient> Patient { get; set; }
        public DbSet<PatientFact> PatientFact { get; set; }
        public DbSet<PatientGroup> PatientGroup { get; set; }
        public DbSet<VaDrug> VaDrug { get; set; }
        public DbSet<Plan> Plan { get; set; }
        public DbSet<PlanFact> PlanFact { get; set; }
        public DbSet<Atom> Atom { get; set; }
        public DbSet<AtomGroup> AtomGroup { get; set; }
        public DbSet<AtomGroupItem> AtomGroupItem { get; set; }
        public DbSet<Rule> Rule { get; set; }
        public DbSet<PlanRules> PlanRule { get; set; }
        public DbSet<Implication> Implication { get; set; }
        public DbSet<RuleImplication> RuleImplication { get; set; }
        public DbSet<AtomFact> AtomFact { get; set; }
    }
}
