//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyAdjudicator.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanRules
    {
        public int PlanRecordId { get; set; }
        public string RuleId { get; set; }
    
        public virtual Rule Rule { get; set; }
        public virtual PlanFact PlanFact { get; set; }
    }
}
