//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyAdjudicator.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanRule
    {
        public long PlanRecordId { get; set; }
        public long RuleId { get; set; }
    
        public virtual Rule Rule { get; set; }
        public virtual PlanDetail PlanFact { get; set; }
    }
}
