//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyAdjudicator.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanDetail
    {
        public PlanDetail()
        {
            this.PlanRules = new HashSet<PlanRule>();
        }
    
        public System.Guid RecordId { get; set; }
        public System.Guid PlanId { get; set; }
        public string Name { get; set; }
        public bool Retraction { get; set; }
        public long OriginalFactRecordId { get; set; }
        public System.DateTime RecordCreatedDateTime { get; set; }
        public string RecordCreatedUser { get; set; }
    
        public virtual ICollection<PlanRule> PlanRules { get; set; }
    }
}
