//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyAdjudicator.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rule
    {
        public Rule()
        {
            this.RuleImplications = new HashSet<RuleImplication>();
            this.PlanRules = new HashSet<PlanRules>();
        }
    
        public long RuleId { get; set; }
        public string RuleType { get; set; }
        public string DefaultValue { get; set; }
    
        public virtual ICollection<RuleImplication> RuleImplications { get; set; }
        public virtual ICollection<PlanRules> PlanRules { get; set; }
    }
}
