//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyAdjudicator.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RuleImplication
    {
        public long RecordId { get; set; }
        public long RuleId { get; set; }
        public System.Guid ImplicationId { get; set; }
        public string Priority { get; set; }
    
        public virtual Rule Rule { get; set; }
        public virtual Implication Implication { get; set; }
    }
}
