//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyAdjudicator.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaDrug
    {
        public string Ndc_1 { get; set; }
        public string Ndc_2 { get; set; }
        public string Ndc_3 { get; set; }
        public string NdfNdc { get; set; }
        public string Upn { get; set; }
        public Nullable<System.DateTime> IDateNdc { get; set; }
        public string Trade { get; set; }
        public string VaProduct { get; set; }
        public Nullable<System.DateTime> IDateVap { get; set; }
        public string ProductNu { get; set; }
        public string FeeDer { get; set; }
        public string Generic { get; set; }
        public decimal PkgSz { get; set; }
        public string PkgType { get; set; }
        public string VaClass { get; set; }
        public string Manufac { get; set; }
        public string StandardMedRoute { get; set; }
        public string Strength { get; set; }
        public string Units { get; set; }
        public string DoseForm { get; set; }
        public string NfName { get; set; }
        public string Csfs { get; set; }
        public string RxOtc { get; set; }
        public string NfIndicat { get; set; }
        public string VaPrn { get; set; }
        public string DispUnt { get; set; }
        public string Id { get; set; }
        public string Mark { get; set; }
    }
}
